# Generated by Django 5.0.1 on 2024-02-05 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='followers',
            field=models.ManyToManyField(related_name='followed_blogs', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики блога'),
        ),
        migrations.CreateModel(
            name='PostUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитан ли пост или нет')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_users', to='blog.post', verbose_name='Прочтенный пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_posts', to=settings.AUTH_USER_MODEL, verbose_name='Прочитанные посты')),
            ],
        ),
    ]
